language: python
python:
  - 3.4

sudo: false

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy

install:
  - pip install coveralls
  - pip install tox

script:
  - tox -e $TOX_ENV

after_script:
  - coveralls
